set autoindent
set backspace=indent,eol,start
set expandtab
set hidden
set hlsearch
set ignorecase
set incsearch
set linebreak
set number
set relativenumber
set ruler
set shiftwidth=2
set showbreak=+++
set showmatch
set smartcase
set smartindent
set smarttab
set softtabstop=2
set undolevels=1000
set wildmenu
