set nocompatible

filetype plugin indent on
syntax on

runtime plugins.vim
runtime colors.vim
runtime mappings.vim
runtime settings.vim

runtime pluginsettings/coc.vim
runtime pluginsettings/fzf.vim
runtime pluginsettings/nerdtree.vim
runtime pluginsettings/prettier.vim
runtime pluginsettings/vim-uninpaired.vim
