set nocompatible

filetype plugin indent on
syntax on

runtime plugins.vim
runtime colors.vim
runtime mappings.vim
runtime settings.vim

runtime pluginsettings/airline.vim
runtime pluginsettings/vim-uninpaired.vim
runtime pluginsettings/netrw.vim
runtime pluginsettings/prettier.vim
runtime pluginsettings/coc.vim
